import {
  ArrowDown,
  ArrowRight,
  Award,
  BookOpen,
  Briefcase,
  Calendar,
  CalendarCheck,
  CalendarPlus,
  ChartNoAxesColumn,
  ChartPie,
  Check,
  ChevronDown,
  CircleCheck,
  CirclePlay,
  CircleX,
  Clock,
  CloudDownload,
  Compass,
  Download,
  DraftingCompass,
  ExternalLink,
  FileDown,
  FileText,
  FolderOpen,
  Globe,
  GraduationCap,
  HandHeart,
  Handshake,
  Headphones,
  Headset,
  IdCard,
  Info,
  LaptopMinimal,
  Lightbulb,
  Link,
  Linkedin,
  ListChecks,
  LoaderCircle,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  MessagesSquare,
  Mic,
  Mountain,
  Music2,
  Network,
  Pause,
  Phone,
  Play,
  Podcast,
  Presentation,
  Printer,
  Receipt,
  ReceiptText,
  RotateCcw,
  RotateCw,
  Search,
  Settings,
  ShieldCheck,
  Sprout,
  Star,
  Target,
  TrendingUp,
  User,
  UserCheck,
  UserRound,
  Users,
  UsersRound,
  Video,
  X,
  Youtube,
  Zap,
} from 'lucide-react';
import type { LucideProps } from 'lucide-react';

/**
 * The prototype was drawn with FontAwesome loaded from a CDN — a render-blocking
 * stylesheet plus webfonts for the sake of a few dozen glyphs. These are the
 * same icons as Lucide components, so only the ones actually used ship, and
 * nothing is fetched from a third party.
 */
const ICONS = {
  'linkedin': Linkedin,
  'linkedin-in': Linkedin,
  'spotify': Music2,
  'youtube': Youtube,
  'calendar-plus': CalendarPlus,
  'circle-play': CirclePlay,
  'clock': Clock,
  'folder-open': FolderOpen,
  'user': User,
  'arrow-down': ArrowDown,
  'arrow-right': ArrowRight,
  'arrow-up-right-from-square': ExternalLink,
  'award': Award,
  'bars': Menu,
  'bolt': Zap,
  'book-open': BookOpen,
  'briefcase': Briefcase,
  'bullhorn': Megaphone,
  'bullseye': Target,
  'calendar': Calendar,
  'calendar-check': CalendarCheck,
  'certificate': Award,
  'chalkboard-user': Presentation,
  'chart-line': TrendingUp,
  'chart-pie': ChartPie,
  'check': Check,
  'check-circle': CircleCheck,
  'chevron-down': ChevronDown,
  'circle-check': CircleCheck,
  'circle-info': Info,
  'circle-xmark': CircleX,
  'cloud-arrow-down': CloudDownload,
  'comments': MessagesSquare,
  'compass': Compass,
  'compass-drafting': DraftingCompass,
  'download': Download,
  'earth-americas': Globe,
  'envelope': Mail,
  'file-arrow-down': FileDown,
  'file-contract': FileText,
  'file-invoice': ReceiptText,
  'file-pdf': FileText,
  'gear': Settings,
  'globe': Globe,
  'graduation-cap': GraduationCap,
  'hands-holding': HandHeart,
  'handshake-simple': Handshake,
  'headphones': Headphones,
  'headset': Headset,
  'id-badge': IdCard,
  'laptop-file': LaptopMinimal,
  'lightbulb': Lightbulb,
  'link': Link,
  'list-check': ListChecks,
  'location-dot': MapPin,
  'lock': Lock,
  'magnifying-glass': Search,
  'magnifying-glass-chart': ChartNoAxesColumn,
  'microphone-lines': Mic,
  'mountain': Mountain,
  'pause': Pause,
  'people-group': Users,
  'phone': Phone,
  'play': Play,
  'podcast': Podcast,
  'print': Printer,
  'receipt': Receipt,
  'rotate-left': RotateCcw,
  'rotate-right': RotateCw,
  'seedling': Sprout,
  'shield-halved': ShieldCheck,
  'sitemap': Network,
  'spinner': LoaderCircle,
  'star': Star,
  'user-doctor': UserRound,
  'user-group': Users,
  'user-shield': UserCheck,
  'user-tie': UserRound,
  'users': Users,
  'users-gear': UsersRound,
  'video': Video,
  'xmark': X,
} as const;

export type IconName = keyof typeof ICONS;

type Props = LucideProps & { name: IconName };

export default function Icon({ name, strokeWidth = 2.25, ...rest }: Props) {
  const Cmp = ICONS[name];
  if (!Cmp) return null;
  return <Cmp aria-hidden strokeWidth={strokeWidth} {...rest} />;
}
